source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'savon', '~> 2.0'
gem 'jazz_hands'
