# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2535f771b9ecb42aff70073428a93ddc9e6012abddebe87b1efc50bb43256a91ff38315f9097a62e7a88e9c8609bf388560c168a8b02bc77a3656deefcaab1a9

test:
  secret_key_base: 1e9672a19ce709ff511a4cb2851cbc4a64f6dbeb5bd791881ac88f4de7a8ba8ca7054addd0cc61fe0aadcaa0a66b346621d5c27b0ebf25ae68ddaa5941509a75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
